#!/usr/bin/env python3
"""Emit LaTeX fragment banks from data/questions.json and optional question_tags.yaml."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from exam_toolkit.latex_escape import latex_escape_plain
from exam_toolkit.paths import (
    BUILD_LATEX_DIR,
    DATA_DIR,
    QUESTIONS_JSON,
    QUESTION_TAGS_YAML,
)
from exam_toolkit.tags import effective_category, load_question_tags


def question_tex_block(q: dict, eff_cat: str) -> str:
    qid = latex_escape_plain(q["id"])
    meta = latex_escape_plain(
        f"{q['source_pdf']} #{q['number_in_pdf']} · {eff_cat}"
        + (" · T/F" if q.get("is_true_false") else "")
    )
    body_lines = q["body_plain"].split("\n")
    body = "\n".join(latex_escape_plain(L) + r"\\" for L in body_lines)
    return (
        f"\\subsection*{{\\texttt{{{qid}}}}}\n"
        f"\\textit{{{meta}}}\\par\\smallskip\n"
        "\\begin{quote}\n\\small\\sloppy\n"
        f"{body}\n"
        "\\end{quote}\n\n"
    )


def write_bank(path: Path, title: str, blocks: list[str]) -> None:
    header = (
        "% Auto-generated by build_latex.py — do not edit by hand.\n"
        f"% {title}\n\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(header + "".join(blocks), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--questions", type=Path, default=QUESTIONS_JSON)
    parser.add_argument("--tags", type=Path, default=QUESTION_TAGS_YAML)
    parser.add_argument("--out-dir", type=Path, default=BUILD_LATEX_DIR)
    args = parser.parse_args()

    if not args.questions.is_file():
        print(f"Missing {args.questions}; run extract_questions.py first.", file=sys.stderr)
        raise SystemExit(1)

    questions: list[dict] = json.loads(args.questions.read_text(encoding="utf-8"))
    try:
        tags = load_question_tags(args.tags)
    except (RuntimeError, ValueError) as e:
        print(e, file=sys.stderr)
        raise SystemExit(1) from e

    all_blocks: list[str] = []
    t1_blocks: list[str] = []
    t2_blocks: list[str] = []

    for q in questions:
        eff = effective_category(q, tags)
        block = question_tex_block(q, eff)
        all_blocks.append(block)
        if eff == "test1":
            t1_blocks.append(block)
        elif eff == "test2":
            t2_blocks.append(block)

    out_dir: Path = args.out_dir
    write_bank(out_dir / "exam_bank.tex", "Full question bank", all_blocks)
    write_bank(out_dir / "test1_bank.tex", "Test 1–tagged questions only", t1_blocks)
    write_bank(out_dir / "test2_bank.tex", "Test 2–tagged questions only", t2_blocks)

    print(
        f"Wrote exam_bank.tex ({len(all_blocks)}), "
        f"test1_bank.tex ({len(t1_blocks)}), test2_bank.tex ({len(t2_blocks)}) under {out_dir}"
    )


if __name__ == "__main__":
    main()
